# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 657fc1441d5d6437c530dec1691dec94f4370afff5681f774e1560eac7cd0fc78cc668c766f50a8feaeb6493055b964595dc9f60973864e3a56ba3d9fee0a15d

test:
  secret_key_base: 5e4fad29235e84463fa7eb055890f97b864a927a6257d61d76ac87988144fd35ba419f768eadd64ac6bf0068968ba0db7cedc63a97953ea6a54f790d830b6396

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
